package dev.minebleach.reiatsutest.client.hud;

import java.util.Map;

/** GENERATED by tools/gen_hud_textures.py: positions of the sheets inside textures/gui/hud/hud_atlas.png (x, y, w, h). */
final class HudAtlasLayout {
	static final int SIZE = 512;
	static final Map<String, int[]> SHEETS = Map.ofEntries(
		Map.entry("ability_icons", new int[] {350, 0, 64, 48}),
		Map.entry("bar_fill", new int[] {161, 229, 124, 35}),
		Map.entry("bar_frame", new int[] {118, 303, 128, 11}),
		Map.entry("bar_sheen", new int[] {286, 303, 14, 7}),
		Map.entry("cooldown_sweep", new int[] {229, 0, 120, 80}),
		Map.entry("emblem_fill", new int[] {392, 270, 30, 30}),
		Map.entry("emblem_frame", new int[] {301, 270, 90, 30}),
		Map.entry("emblem_icons", new int[] {0, 303, 32, 16}),
		Map.entry("gem", new int[] {247, 303, 28, 9}),
		Map.entry("key_tab", new int[] {276, 303, 9, 9}),
		Map.entry("pixel", new int[] {301, 303, 4, 4}),
		Map.entry("ring_shatter", new int[] {0, 229, 160, 40}),
		Map.entry("slot_frame", new int[] {423, 270, 88, 22}),
		Map.entry("timer_ring", new int[] {0, 0, 228, 228}),
		Map.entry("title_band", new int[] {0, 270, 300, 32}),
		Map.entry("toast_line", new int[] {306, 303, 96, 3}),
		Map.entry("voice_mic", new int[] {33, 303, 84, 12})
	);

	private HudAtlasLayout() {
	}
}
