package dev.minebleach.reiatsutest.client.hud;

import dev.minebleach.reiatsutest.ReiatsuTest;
import dev.minebleach.reiatsutest.client.fx.FxMath;
import dev.minebleach.reiatsutest.core.state.CharacterId;
import dev.minebleach.reiatsutest.core.state.ZanpakutoState;
import net.minecraft.util.Identifier;

/** Texture ids, sheet geometry and palettes of the HUD (VFX_STORYBOARD 7.1, 7.10; generated by tools/gen_hud_textures.py). */
public final class HudAssets {
	private static Identifier t(String n) {
		return ReiatsuTest.id("textures/gui/hud/" + n + ".png");
	}

	public static final Identifier PLATE_SHADOW = t("plate_shadow"); // 192 x 48
	public static final Identifier EMBLEM_FRAME = t("emblem_frame"); // 3 x 30 x 30
	public static final Identifier EMBLEM_FILL = t("emblem_fill"); // 30 x 30
	public static final Identifier EMBLEM_ICONS = t("emblem_icons"); // 2 x 16 x 16
	public static final Identifier TIMER_RING = t("timer_ring"); // 6 x 6 frames of 38
	public static final Identifier RING_SHATTER = t("ring_shatter"); // 4 x 40 x 40
	public static final Identifier BAR_FRAME = t("bar_frame"); // 128 x 11
	public static final Identifier BAR_FILL = t("bar_fill"); // 124 x 35
	public static final Identifier BAR_OVERLAY = t("bar_overlay"); // 64 x 14
	public static final Identifier BAR_SHEEN = t("bar_sheen"); // 14 x 7
	public static final Identifier GEM = t("gem"); // 4 x 7 x 9
	public static final Identifier HATCH = t("hatch"); // 4 x 4
	public static final Identifier SLOT_FRAME = t("slot_frame"); // 4 x 22 x 22
	public static final Identifier SLOT_GLOW = t("slot_glow"); // 28 x 28
	public static final Identifier COOLDOWN_SWEEP = t("cooldown_sweep"); // 24 frames of 20 x 20 (6 x 4)
	public static final Identifier KEY_TAB = t("key_tab"); // 9 x 9
	public static final Identifier ABILITY_ICONS = t("ability_icons"); // 4 x 3 of 16 x 16
	public static final Identifier VOICE_MIC = t("voice_mic"); // 7 x 12 x 12
	public static final Identifier TITLE_BAND = t("title_band"); // 300 x 32
	public static final Identifier TITLE_GLOW = t("title_glow"); // 96 x 48
	public static final Identifier TOAST_LINE = t("toast_line"); // 96 x 3
	public static final Identifier PIXEL = t("pixel"); // 4 x 4 white, for batched solid rectangles
	public static final Identifier TOAST_SPRITE = ReiatsuTest.id("hud/toast");

	public static final float[] INK = FxMath.hex("#0B0F1A");
	public static final float[] TEXT = FxMath.hex("#E8ECF4");
	public static final float[] DIM = FxMath.hex("#8A93A6");
	public static final float[] GOLD = FxMath.hex("#E8C66A");
	public static final float[] WARN = FxMath.hex("#FF6A5A");
	public static final float[] OK = FxMath.hex("#4ADE80");
	public static final float[] ERROR = FxMath.hex("#F87171");
	public static final float[] WHITE = {1f, 1f, 1f};
	public static final float[] STEEL = FxMath.hex("#C8D2DC");

	private HudAssets() {
	}

	/** Accent colour (frame, text) of a character in a state (7.1). BASE is drawn like SEALED. */
	public static float[] accent(CharacterId c, ZanpakutoState s) {
		if (c == CharacterId.RUKIA) {
			return s == ZanpakutoState.BANKAI ? FxMath.hex("#DDF3FF") : s == ZanpakutoState.SHIKAI ? FxMath.hex("#9ED3F0") : STEEL;
		}
		if (c == CharacterId.BYAKUYA) {
			return s == ZanpakutoState.BANKAI ? FxMath.hex("#F3E4FF") : s == ZanpakutoState.SHIKAI ? FxMath.hex("#E5A4DC") : STEEL;
		}
		return STEEL;
	}

	/** Row of {@code bar_fill.png}: 0 sealed, 1 Rukia shikai, 2 Rukia bankai, 3 Byakuya shikai, 4 Byakuya bankai. */
	public static int fillRow(CharacterId c, ZanpakutoState s) {
		if (s == ZanpakutoState.SHIKAI || s == ZanpakutoState.BANKAI) {
			int base = c == CharacterId.BYAKUYA ? 3 : 1;
			return base + (s == ZanpakutoState.BANKAI ? 1 : 0);
		}
		return 0;
	}

	/** Diamond fill colour behind the emblem icon. */
	public static float[] emblemFill(CharacterId c) {
		return c == CharacterId.BYAKUYA ? FxMath.hex("#1C2540") : FxMath.hex("#1E4C86");
	}
}
